// <auto-generated />
namespace ModelDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class sa2022413 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sa2022413));
        
        string IMigrationMetadata.Id
        {
            get { return "202204131130377_sa2022413"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
