// <auto-generated />
namespace ModelDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _20220324S : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20220324S));
        
        string IMigrationMetadata.Id
        {
            get { return "202203240909262_20220324S"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
