// <auto-generated />
namespace ModelDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _20220328Sa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20220328Sa));
        
        string IMigrationMetadata.Id
        {
            get { return "202203281157275_20220328Sa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
