// <auto-generated />
namespace ModelDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Saif20_08_2022 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Saif20_08_2022));
        
        string IMigrationMetadata.Id
        {
            get { return "202208200818414_Saif20_08_2022"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
